import pandas as pd
import numpy as np

df = pd.read_csv("./dogNames2.csv")
# print(df.head())
# print(df.info())

df = df.sort_values(by="Count_AnimalName", ascending=False)
# print(df.head(5))
# print(df[:20])
# # print(df[:20]["Row_Labels"])
# print(df[df["Count_AnimalName"] > 800])
# print(df[(df["Count_AnimalName"] > 800) & (df["Count_AnimalName"] < 1000)])
# print(df[(df["Count_AnimalName"] > 700) & (df["Row_Labels"].str.len() > 4)])
# print(pd.isnull(df))
# print(pd.notnull(df))

t = pd.DataFrame(np.arange(12).reshape(3, 4), index=list("ABC"), columns=list("WXYZ"))
print(t)
# print(t.loc["A", "X"])
# print(t.loc["A", ["W", "Z"]])
# print(t.loc["A"])
# print(t.loc[:, "W"])
# print(t.loc["A", :])
# print(t.loc[["A", "C"], :])
# print(t.loc[:, ["X", "Z"]])
# print(t.loc[["A", "B"], ["X", "Z"]])
# print(t.iloc[0, 1])
# print(t.iloc[0, [0, 3]])
# print(t.iloc[0])
# print(t.iloc[:, 0])
# print(t.iloc[0, :])
# print(t.iloc[[0, 2], :])
# print(t.iloc[0, [1, 3]])
# print(t.iloc[0, 1:4])
# print(t.iloc[[0, 2], [1, 3]])
# print(t.iloc[:, [2, 1]])
# print(t.iloc[[0, 2], [2, 1]])
# print(t.iloc[1:, 2:])
t.iloc[1:, :2] = 30
print(t)
# print(t.iloc[1:, :2])
t.iloc[1:, :2] = np.nan
print(t)